"use client";

import { motion } from "framer-motion";

export default function GalleryPage() {
  // Placeholder representations for gallery items
  const galleryItems = [
    { id: 1, title: "Urban Chic", style: "from-primary/20 to-secondary/20" },
    { id: 2, title: "Summer Breeze", style: "from-primary/10 to-primary/30" },
    { id: 3, title: "Evening Elegance", style: "from-secondary/20 to-foreground/10" },
    { id: 4, title: "Streetwear", style: "from-foreground/5 to-primary/20" },
    { id: 5, title: "Minimalist Fall", style: "from-secondary/10 to-primary/10" },
    { id: 6, title: "Avant-Garde", style: "from-primary/30 to-foreground/5" },
  ];

  return (
    <main className="min-h-screen pt-32 pb-16 px-6 max-w-7xl mx-auto">
      <div className="text-center mb-16">
        <h1 className="text-5xl font-bold mb-4">Inspiration <span className="text-primary">Gallery</span></h1>
        <p className="text-foreground/60 max-w-xl mx-auto">
          Explore outfits generated by the Aura-Fit community. Discover the limitless potential of AI digital styling.
        </p>
      </div>

      <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
        {galleryItems.map((item, i) => (
          <motion.div
            key={item.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: i * 0.1 }}
            className={`relative group rounded-3xl overflow-hidden shadow-2xl break-inside-avoid aspect-[3/4] bg-gradient-to-br ${item.style} flex flex-col justify-end p-6 border border-border`}
          >
            <div className="absolute inset-0 bg-background/0 group-hover:bg-background/20 transition-colors duration-300" />
            <div className="relative z-10 transform translate-y-4 group-hover:translate-y-0 opacity-80 group-hover:opacity-100 transition-all duration-300">
              <h3 className="text-xl font-medium text-foreground">{item.title}</h3>
              <p className="text-sm text-foreground/60 font-medium tracking-wide">AI Generative Placeholder</p>
            </div>
          </motion.div>
        ))}
      </div>
    </main>
  );
}
